#!/bin/bash

subj_id=515697
ses_id=15mo
data_dir=/tmp/UNC_BCP
data_bucket=s3://UNC_BCP
run_dir=/home/faird/shared/code/internal/utilities/slurm_pipeline_wrappers/slurm_BCP_dcan_infantwrapper_anatonly
singularity=`which singularity`

BIDS_DIR=${data_dir}/sub-${subj_id}
OUTPUT_DIR=${data_dir}/processed/dcan-infant-pipeline

# pull down needed data and files from BIDS bucket
if [ ! -d ${data_dir}/sub-${subj_id}/ses-${ses_id} ]; then
	mkdir -p ${BIDS_DIR}
	s3cmd get ${data_bucket}/sub-${subj_id}/ses-${ses_id} ${BIDS_DIR} --recursive -v
fi
if [ ! -e ${data_dir}/dataset_description.json ]; then
	cp ${run_dir}/dataset_description.json ${data_dir}
fi
if [ ! -e ${data_dir}/participants.tsv ]; then
	s3cmd get ${data_bucket}/participants.tsv ${data_dir} -v 
fi

# create processed and derivatives folders if they do not exist
if [ ! -d ${data_dir}/processed/dcan-infant-pipeline ]; then
	mkdir ${data_dir}/processed/
	mkdir ${data_dir}/processed/dcan-infant-pipeline/
fi

fez_internal_pl=/home/feczk001/shared/code/internal/pipelines

infant_abcd_bids_pipeline=${fez_internal_pl}/DCAN-infant-BIDS/infant-abcd-bids-pipeline_dbp-hotfix-03172022.sif

echo ${infant_abcd_bids_pipeline}

#THIS IS BCP SPECIFIC
if [ ${#ses_id} -ge 4 ] && [ ${ses_id:2} == 'mo' ]; then
MONTH=${ses_id:0:2}
elif [ ${#ses_id} -ge 3 ] && [ ${ses_id:1} == 'mo' ]; then
MONTH=${ses_id:0:1}
elif [ ${#ses_id} -ge 3 ] && [ ${ses_id:1} == 'wk' ]; then
MONTH=0
elif [ ${#ses_id} -ge 4 ] && [ ${ses_id:2} == 'wk' ]; then
MONTH=0
fi


if   [ "${MONTH}" -lt 0 ]; then
    echo "Invalid month <0: ${MONTH}, exiting"
    exit 1
elif [ "${MONTH}" -le 2 ] ; then
    template=00-02
elif [ "${MONTH}" -le 5 ] ; then
    template=02-05
elif [ "${MONTH}" -le 11 ] ; then
    template=08-11
elif [ "${MONTH}" -le 14 ] ; then
    template=11-14
elif [ "${MONTH}" -le 17 ] ; then
    template=14-17
elif [ "${MONTH}" -le 21 ] ; then
    template=17-21
elif [ "${MONTH}" -le 27 ] ; then
    template=21-27
elif [ "${MONTH}" -le 33 ] ; then
    template=27-33
elif [ "${MONTH}" -le 44 ] ; then
    template=33-44
elif [ "${MONTH}" -le 60 ] ; then
    template=44-60
else
    echo "Invalid month >60 ${MONTH}, exiting."
    exit 1
fi

BANDSTOP="16.8896 28.6662"
FS_LICENSE=/home/faird/shared/code/external/utilities/freesurfer_license
HNM=ROI_IPS
SMM=ROI_MAP
DCMETHOD=NONE
TEMPLATE_BIND=/home/elisonj/shared/BCP/lib/templates/${template}
NCPUS=12

lic_loc=/opt/freesurfer/license.txt

singularity run --cleanenv \
-e \
-B ${data_dir}:/bids_input \
-B ${OUTPUT_DIR}:/output \
-B ${FS_LICENSE}/license.txt:${lic_loc} \
-B ${TEMPLATE_BIND}:/opt/pipeline/global/templates \
${infant_abcd_bids_pipeline} \
--freesurfer-license ${lic_loc} \
--participant-label ${subj_id} \
--session-id ${ses_id} \
--bandstop ${BANDSTOP} \
--hyper-normalization-method ${HNM} \
--subcortical-map-method ${SMM} \
--dcmethod ${DCMETHOD} \
--ncpus ${NCPUS} \
--stage "PreFreeSurfer:ExecutiveSummary" \
--atropos-mask-method NONE \
--anat-only \
/bids_input \
/output


#push processed outputs to bucket
s3cmd sync -F --recursive -v ${OUTPUT_DIR}/sub-${subj_id}/ses-${ses_id}/ ${data_bucket}/processed/dcan-infant-pipeline/sub-${subj_id}/ses-${ses_id}/

# run filemapper






